version: '3.8'

services:
  # Neo4j Community Edition Database
  neo4j:
    image: neo4j:5.15-community
    container_name: constellation-neo4j
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/constellation123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - constellation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "constellation123", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # FastAPI Backend Application
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: constellation-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=constellation123
      - NEO4J_DATABASE=neo4j
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Constellation CMDB
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:8080"]
      - SECRET_KEY=constellation-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_MINUTES=60
    volumes:
      - ./backend:/app
      - constellation_uploads:/app/uploads
    networks:
      - constellation-network
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

  # Frontend Vue.js Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: constellation-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - VITE_NEO4J_BROWSER_URL=http://localhost:7474
    networks:
      - constellation-network
    depends_on:
      - api
    restart: unless-stopped

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  constellation_uploads:
    driver: local

networks:
  constellation-network:
    driver: bridge
    name: constellation-network